sudo: false
cache: bundler
language: ruby

rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 5"

script:
  - bundle exec rspec
  - bundle exec rubocop
